server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: moto-service
eureka:
  client:
    fetch-regostry: true
    registerWithEureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}