server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/dgarcia92/microservicios-autos-motos
          search-paths: config-data 
  application:
    name: config-service